### PR TITLE
frontend-UI-design

### PR DESCRIPTION
**Pull request by jstavh**
Progress on tasks listed in Monday

### CODE REVIEW

**Comment by mxnkarou** [comment]
Some conflicts have to be resolved! I can merge then :)

**Comment by jstavh** [comment]
> Some conflicts have to be resolved! I can merge then :)

Yes working on this; these conflicts have to do with the test files that are ignored

**Review by mxnkarou — APPROVED** [review]
Great stuff! No comments from me =)! 🥳

**Comment by jstavh** [comment]
> Great stuff! No comments from me =)! 🥳

Thank you! Let's go!

**Pull request merged**
