### PR TITLE
feat/client

### PR DESCRIPTION
**Pull request by jstavh**
Nicole advise to change instructions per this Monday task: https://granola-bunch.monday.com/boards/3358491340/pulses/3536903013

### CODE REVIEW

**Comment by jstavh** [comment]
We need a link or page for FAQ (currently incorrectly linked to faucet), before we push and merge to staging.

**Review by mxnkarou — CHANGES_REQUESTED** [review]
There are some build errors that would need to be fixed

**Comment by jstavh** [comment]
Build errors occured because the new code needed new snapshot tests that matched correctly. Now fixed. Yet we are waiting on FAQs landing page / pointing to a new URL vs currently the wrong one / placeholder.

**Comment by jstavh** [comment]
Server test is affecting build but this PR has no server changes

**Review by mxnkarou — APPROVED** [review]

**Pull request merged**
